src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Controllers/ContactDataController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace BGL.Web.Halifax.MotorQuote.Controllers
{
    public class ContactDataController : Controller
    {
        public ActionResult HoustonContactData()
        {
            return PartialView("_HoustonContactData");
        }
    }
}

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Controllers/LegalController.cs
using System.Web;
using System.Web.Mvc;
using BGL.Security.Web.Authentication.Controllers;

namespace BGL.Web.Halifax.MotorQuote.Controllers
{
    public class LegalController : SecuredController
    {
        public ActionResult PostPriceImportantInformation()
        {
            return PartialView();
        }

        public ActionResult PrePriceImportantInformation()
        {
            return PartialView();
        }

        public ActionResult IntermediaryServicesContractSummary()
        {
            return PartialView();
        }

        public ActionResult Direct()
        {
            return View();
        }

        public ActionResult DirectPrePriceLegal()
        {
            return View();
        }

        public ActionResult AboutUs()
        {
            return PartialView();
        }

        public ActionResult QuoteAcceptanceInformation()
        {
            return PartialView();
        }
    }
}

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Controllers/PaymentController.cs
using System.Web.Mvc;
using BGL.Security.Web.Authentication.Controllers;

namespace BGL.Web.Halifax.MotorQuote.Controllers
{
    public class PaymentController : SecuredController
    {
        public ActionResult PaymentSummary()
        {
            return View();
        }

        public ActionResult Annual()
        {
            return View();
        }

        public ActionResult AnnualSummary()
        {
            return View();
        }

        public ActionResult MonthlyInstalment()
        {
            return View();
        }

        public ActionResult MonthlyInstalmentSummary()
        {
            return View();
        }

        public ActionResult MonthlyDeposit()
        {
            return View();
        }

        public ActionResult MonthlyDepositSummary()
        {
            return View();
        }

        public ActionResult AllDone()
        {
            return View();
        }

        public ActionResult Unsuccessful()
        {
            return View();
        }

        public ActionResult PaymentSuccessful()
        {
            return View();
        }

        public ActionResult PolicyCreationPending()
        {
            return View();
        }
    }
}

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Controllers/SessionTimeoutController.cs
using System.Web.Mvc;

namespace BGL.Web.Halifax.MotorQuote.Controllers
{
    public class SessionTimeoutController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Views/Shared/_AjaxErrorScript.cshtml
@using System.Configuration

<script type="text/javascript">
    $(document).ajaxError(function (xhr, props) {
        if (props.status === 401) {
            location.href = '@(ConfigurationManager.AppSettings["SessionTimeoutRedirectUrl"])';
        }
    });
</script>

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Views/Shared/_Footer.cshtml
@using System.Configuration
@using BGL.Common.Configuration.Interfaces
@using BGL.Components.Footer
@model bool?

@{
    var config = DependencyResolver.Current.GetService<IConfig>();
    var tenantConfiguration = config.GetTenantConfiguration();

    var year = DateTime.Now.Year;
    var copyrightBrandName = "BISL Limited";

    var policyBaseUrl = new Uri(ConfigurationManager.AppSettings["PolicyBaseUrl"]);
    var privacyPolicyUrl = new Uri(policyBaseUrl, "/Legal/PC/Privacy_policy.html");

    var isDirectLayout = Model == true;

    var importantInformationUrl = isDirectLayout
        ? Url.Action("PrePriceImportantInformation", "Legal")
        : Url.Action("PostPriceImportantInformation", "Legal");

    var vaInvocationPoint = "Sales_TE_ContactUs";
}

<footer class="page-footer">
    <div class="page-footer__wrapper">
        <div class="page-footer__section">
            <p class="page-footer__copyright">
                <strong>&copy; @year @copyrightBrandName.</strong>
                <span> All rights reserved.</span>
            </p>
            <ul class="page-footer__list list--horizontal">
                <li class="list__item">
                    <a id="importantInfo" class="page-footer__link" href="#"
                       data-toggle="slide-panel"
                       data-target="#SlidePanel"
                       data-container="SlidePanelContent"
                       data-action-url="@importantInformationUrl">Important info</a>
                </li>
                <span class="page-footer__list-divider">/</span>
                <li class="list__item">
                    <a class="page-footer__link link__new-window white normal" href="@privacyPolicyUrl" rel="noopener" aria-label="Open privacy policy in new window" target="_blank" >Privacy policy</a>
                </li>
                <span class="page-footer__list-divider">/</span>
                <li class="list__item">
                    <a class="page-footer__link va-invocation"
                       href="#"
                       data-va-invocation-point="@vaInvocationPoint"
                       rel="noopener" target="_blank">Contact us</a>
                </li>
            </ul>
        </div>
        
        @if (!isDirectLayout)
        {
            @Html.ComponentRenderFooterDocumentLinks(new ComponentFooterConfiguration
            {
                Id = "Footer",
                TenantConfiguration = tenantConfiguration
            })
        }
    </div>
</footer>

<script type="text/javascript">
    bgl.common.contentpanel.openPanelByClick('importantInfo');
</script>

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Views/Shared/_IntermediaryServiceFee.cshtml
﻿
@using BGL.Common.Configuration.Interfaces
@using BGL.Components.TermsAndConds

@{
    var tenantConfiguration = DependencyResolver.Current.GetService<IConfig>().GetTenantConfiguration();
    var isfFeeConfig = new ComponentTermsAndCondsConfiguration
    {
        Id = "SalesTermsAndConditionsIsfFee",
        TenantConfiguration = tenantConfiguration
    };

}

&pound;@Html.ComponentRenderTermsAndConditionsGetIsfFeeAmount(isfFeeConfig).ToString()

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Views/Shared/_Layout.cshtml
@using System.Configuration
@using System.Security.Claims
@using BGL.Common.BaseApplication.Telemetry
@using BGL.Common.Configuration.Interfaces
@using BGL.Common.ScriptRegister
@using BGL.Common.Utility.Constants
@using BGL.Common.Utility.Extensions
@using BGL.Components.Basket
@using BGL.Components.PageReloader
@using BGL.Components.GoogleTagManager
@using BGL.Components.Houston
@using BGL.Components.Navigation
@using BGL.Components.Navigation.Models
@using BGL.Web.Halifax.MotorQuote.Constants

@{
    var config = DependencyResolver.Current.GetService<IConfig>();
    var vaConfig = config.GetVirtualAssistantConfiguration();
    var tenantConfiguration = config.GetTenantConfiguration();

    var quoteId = (User as ClaimsPrincipal)?.QuoteId().Split('-').FirstOrDefault();

    var bglBundlingEnabled = bool.TryParse(ConfigurationManager.AppSettings["BundlingEnabled"], out var bundlingEnabled) && bundlingEnabled;

    var pagesWithoutBackAction = new List<string>
    {
        Url.Action("AllDone", "Payment"), 
        Url.Action("Index", "SessionTimeout")
    };

    var listOfPageWithAsyncComponents = new List<string>
    {
        Url.Action("Index", "AdditionalDetails"),
        Url.Action("Annual", "Payment"),
        Url.Action("AnnualSummary", "Payment"),
        Url.Action("MonthlyInstalment", "Payment"),
        Url.Action("MonthlyInstalmentSummary", "Payment")
    };

    var logoImagePath = $"{tenantConfiguration.ResourceBasePath}logo-brand.svg";
    var listOfPostQuotePages = new[] { "/pricepresentation", "/extras", "/review", "/payment/" };
    var preQuote = listOfPostQuotePages.All(s => !(bool)(Request?.Url?.AbsolutePath?.ToLower().Contains(s)));

    var ninaPreprod = vaConfig.IsVaLive ? string.Empty : $"window.NinaVars.preprod=true;";
    Html.RegisterScript("window.NinaVars=window.NinaVars||{};window.NinaVars.isSelfService=false;" +
                        $"window.NinaVars.isSales=true;{ninaPreprod}window.siteId='{vaConfig.WebChatAccount}';", ScriptLocation.HeadBottom);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="SvrId" content="TE.NET" />
    <title>@ViewBag.Title - Halifax Insurance</title>
    <link rel="shortcut icon" href="@ConfigurationManager.AppSettings["ApplicationPath"]favi.ico" type="image/x-icon">
    @Styles.Render("~/Content/css")

    @Html.ComponentRenderOneTrust(new ComponentGoogleTagManagerConfiguration
    {
        OneTrustConfiguration = config.GetOneTrustConfiguration(),
    })

    @Scripts.Render("~/bundles/vendor")
    @if (bglBundlingEnabled)
    {
        @Scripts.Render("~/bundles/bgl")
    }
    @Html.ComponentRenderGoogleTagManager(new ComponentGoogleTagManagerConfiguration
    {
        Id = "GoogleTagManager",
        AddOnsList = new List<string>
        {
            "No claims discount protection",
            "Guaranteed Replacement Car",
            "RAC Breakdown Assistance",
            "Keycare",
            "Legal Protection",
            "Personal Accident Cover"
        },
        MarketingSourceSetupList = new List<string> { "comparethemarket", "gocompare", "moneysupermarket", "confusedcom", "quotezonecouk" },
        GtmConfiguration = config.GetGtmConfiguration(),
        TenantConfiguration = tenantConfiguration
    })

    @Html.ComponentRenderGoogleTagManagerDataLayer(new ComponentTagManagerConfiguration
    {
        QuoteTier = "Standard"
    })

    @Html.RenderRegisteredScripts(ScriptLocation.HeadTop)
    @Html.RenderRegisteredScripts(ScriptLocation.HeadBottom)
    @Html.RegisterTelemetryScript()

    @Html.ComponentRenderGoogleTagManagerTagManager(new ComponentTagManagerConfiguration
    {
        TagManagerScriptUrl = ConfigurationManager.AppSettings["TagManagerScriptUrl"]
    })
</head>
<body>
    @Html.RenderRegisteredScripts(ScriptLocation.BodyTop)
    <a href="#" id="header-focus" class="hide" tabindex="-1">header focus</a>
    <a class="skip-to-main-content" data-testid="header__skip-to-main-content" href="#main-content">Skip to main content</a>
    <div class="all-content">

        @if (IsSectionDefined("Header"))
        {
            @RenderSection("Header")
        }
        else
        {
            <header class="page-headerv2" id="fixed-header">
                <div class="page-headerv2__wrapper">
                    <div class="page-headerv2__section page-headerv2__section--logo">
                        <img class="page-header__logo" src="@logoImagePath" alt="Halifax" />
                    </div>
                    <div class="page-headerv2__section page-headerv2__section--breadcrumbs">
                        @if (IsSectionDefined("Navigation"))
                        {
                            @RenderSection("Navigation")
                        }
                        else
                        {
                            @Html.ComponentRenderNavigation(new ComponentNavigationConfiguration
                            {
                                Id = "NavigationDefault",
                                MenuKeyPointsConfig = new Dictionary<string, MenuItemConfig>
                                {
                                    { "Quote", new MenuItemConfig
                                    {
                                        ParentAction = Url.Action("Index", "PricePresentation")
                                    }},
                                    { "Extras", new MenuItemConfig
                                    {
                                        ParentAction = Url.Action("Index", "Extras")
                                    }},
                                    { "Review", new MenuItemConfig
                                    {
                                        ParentAction = Url.Action("Index", "Review"),
                                        ChildActions = new List<string>
                                        {
                                            Url.Action("Index", "AdditionalDetails")
                                        }
                                    }},
                                    { "Pay", new MenuItemConfig
                                    {
                                        ParentAction = Url.Action("PaymentSummary", "Payment"),
                                        ChildActions = new List<string>
                                        {
                                            Url.Action("Annual", "Payment"),
                                            Url.Action("AnnualSummary", "Payment"),
                                            Url.Action("MonthlyInstalment", "Payment"),
                                            Url.Action("MonthlyInstalmentSummary", "Payment"),
                                            Url.Action("MonthlyDeposit", "Payment"),
                                            Url.Action("MonthlyDepositSummary", "Payment"),
                                            Url.Action("Unsuccessful", "Payment")
                                        }
                                    }},
                                    { "Done", new MenuItemConfig { ParentAction = Url.Action("AllDone", "Payment") }}
                                },
                                TenantConfiguration = tenantConfiguration
                            })
                        }
                    </div>
                    <div class="page-headerv2__section page-headerv2__section--quote">
                        <div class="pquote-number">
                            <p class="pquote-number__text">
                                <span class="pquote-number__sub-text">Quote number</span>
                                <span class="pquote-number__number">@quoteId</span>
                            </p>
                        </div>
                    </div>
                    <div class="page-headerv2__section page-headerv2__section--basket">
                        @Html.ComponentRenderBasket(new ComponentBasketConfiguration
                        {
                            Id = "Basket",
                            CoverListPriority = new List<string>
                            {
                                FeatureServiceConstants.CoverLevel,
                                FeatureServiceConstants.NcdProtection,
                                FeatureServiceConstants.PriceProtection,
                                FeatureServiceConstants.LegalProtection,
                                FeatureServiceConstants.GuaranteedReplacementVehicle,
                                FeatureServiceConstants.Breakdown,
                                FeatureServiceConstants.KeyCover
                            },
                            AvivaCreditPhoneNumber = BrandConstants.ContactPhoneNumber,
                            ComponentUrl = Url.Action("Basket", "BasketComponent"),
                            TenantConfiguration = config.GetTenantConfiguration()
                        })
                    </div>
                </div>
            </header>
        }

        <main id="main-content">
            @RenderBody()
        </main>

        @Html.Partial("_SlidePanel")

        @if (IsSectionDefined("Footer"))
        {
            @RenderSection("Footer")
        }
        else
        {
            @Html.Partial("_Footer")
        }

        @Html.ComponentRenderPageReloader(new ComponentPageReloaderConfiguration
        {
            Id = "PageReloader",
            TenantConfiguration = tenantConfiguration
        })
        @{
            var componentHoustonConfiguration = new ComponentHoustonConfiguration
            {
                Id = "Houston",
                Brand = vaConfig.BrandName,
                LivePersonBrand = vaConfig.LivePersonBrandName,
                Application = vaConfig.Application,
                JourneySection = "Purchase",
                Product = vaConfig.Product,
                Journey = "Car",
                InvocationPoint = vaConfig.DefaultInvocationPoint,
                PageNamePrefix = "Sales_TE_",
                TenantConfiguration = tenantConfiguration,
                IsPreQuote = preQuote,
                ContactDataUrl = Url.Action("HoustonContactData", "ContactData"),
                OnError = Request.Url.AbsolutePath.ToLower().Contains("error"),
            };
        }
    </div>

    <aside>
        @Html.ComponentRenderHouston(componentHoustonConfiguration)
    </aside>

    <script src="@Url.Content(ConfigurationManager.AppSettings["Nina-Block-Path"])"></script>

    @RenderSection("scripts", required: false)
    @Html.RegisterNavigationOppsPageBackButtonInitScript(pagesWithoutBackAction, listOfPageWithAsyncComponents)
    @Html.RenderRegisteredScripts(ScriptLocation.BodyBottom)
    @Html.Partial("_AjaxErrorScript")
    @Html.ComponentRenderGoogleTagManagerLaunchScript(new ComponentTagManagerConfiguration { })
</body>
</html>

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Views/Shared/_LayoutMainContent.cshtml
@using System.Configuration
@using BGL.Common.BaseApplication.Telemetry
@using BGL.Common.Configuration.Interfaces
@using BGL.Common.ScriptRegister
@using BGL.Components.GoogleTagManager
@using BGL.Components.Houston
@using BGL.Web.Halifax.MotorQuote.Constants

@{
    var config = DependencyResolver.Current.GetService<IConfig>();

    var tenantConfiguration = config.GetTenantConfiguration();
    var vaConfig = config.GetVirtualAssistantConfiguration();
    var bglBundlingEnabled = bool.TryParse(ConfigurationManager.AppSettings["BundlingEnabled"], out var bundlingEnabled) && bundlingEnabled;

    var componentHoustonConfiguration = new ComponentHoustonConfiguration
    {
        Id = "Houston",
        Brand = vaConfig.BrandName,
        LivePersonBrand = vaConfig.LivePersonBrandName,
        Application = vaConfig.Application,
        JourneySection = string.Empty,
        Product = vaConfig.Product,
        Journey = "Car",
        ContactDataUrl = Url.Action("HoustonContactData", "ContactData"),
        InvocationPoint = vaConfig.DefaultInvocationPoint,
        PageNamePrefix = "Sales_TE_",
        TenantConfiguration = tenantConfiguration,
        IsPreQuote = false,
        OnError = Request.Url.AbsolutePath.ToLower().Contains("error"),
    };
    var ninaPreprod = vaConfig.IsVaLive ? string.Empty : $"window.NinaVars.preprod=true;";
    Html.RegisterScript("window.NinaVars=window.NinaVars||{};window.NinaVars.isSelfService=false;" +
                        $"window.NinaVars.isSales=true;{ninaPreprod}window.siteId='{vaConfig.WebChatAccount}';", ScriptLocation.HeadBottom);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="SvrId" content="TE.NET" />
    <title>@ViewBag.Title - Halifax Insurance</title>
    <link rel="shortcut icon" href="@ConfigurationManager.AppSettings["ApplicationPath"]favi.ico" type="image/x-icon">
    @Styles.Render("~/Content/css")

    @Html.ComponentRenderOneTrust(new ComponentGoogleTagManagerConfiguration
    {
        OneTrustConfiguration = config.GetOneTrustConfiguration(),
    })

    @Scripts.Render("~/bundles/vendor")
    @if (bglBundlingEnabled)
    {
        @Scripts.Render("~/bundles/bgl")
    }
    @Html.ComponentRenderGoogleTagManager(new ComponentGoogleTagManagerConfiguration
    {
        Id = "GoogleTagManager",
        GtmConfiguration = config.GetGtmConfiguration(),
        IgnoreSource = true,
        TenantConfiguration = config.GetTenantConfiguration()
    })

    @Html.ComponentRenderGoogleTagManagerDataLayer(new ComponentTagManagerConfiguration
    {
        QuoteTier = "Standard"
    })

    @Html.RenderRegisteredScripts(ScriptLocation.HeadTop)
    @Html.RenderRegisteredScripts(ScriptLocation.HeadBottom)
    @Html.RegisterTelemetryScript()

    @Html.ComponentRenderGoogleTagManagerTagManager(new ComponentTagManagerConfiguration
    {
        TagManagerScriptUrl = ConfigurationManager.AppSettings["TagManagerScriptUrl"]
    })
</head>
<body>
    @Html.RenderRegisteredScripts(ScriptLocation.BodyTop)
    <header class="page-header page-header--minimal" id="fixed-header">
        <div class="page-header__wrapper">
            <div class="page-header__section page-header__section--left">
                <img class="page-header__logo" src="@(config.GetTenantConfiguration().ResourceBasePath)logo-brand.svg" alt="Halifax" />
            </div>
        </div>
    </header>
    <main id="main-content">
        @RenderBody()
    </main>

    <aside>
        @Html.ComponentRenderHouston(componentHoustonConfiguration)
    </aside>

    <script src="@Url.Content(ConfigurationManager.AppSettings["Nina-Block-Path"])"></script>

    @RenderSection("scripts", required: false)
    @Html.RenderRegisteredScripts(ScriptLocation.BodyBottom)
    @Html.Partial("_AjaxErrorScript")
    @Html.ComponentRenderGoogleTagManagerLaunchScript(new ComponentTagManagerConfiguration { })
</body>
</html>

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Views/Shared/_PageAsSliderLayout.cshtml
@using System.Configuration
@using System.Security.Claims
@using BGL.Common.BaseApplication.Telemetry
@using BGL.Common.Configuration.Interfaces
@using BGL.Common.ScriptRegister
@using BGL.Common.Utility.Constants
@using BGL.Common.Utility.Extensions
@using BGL.Components.Basket
@using BGL.Components.PageReloader
@using BGL.Components.GoogleTagManager
@using BGL.Components.Houston
@using BGL.Components.Navigation
@using BGL.Components.Navigation.Models
@using BGL.Web.Halifax.MotorQuote.Constants

@{
    var config = DependencyResolver.Current.GetService<IConfig>();
    var vaConfig = config.GetVirtualAssistantConfiguration();
    var tenantConfiguration = config.GetTenantConfiguration();

    var quoteId = (User as ClaimsPrincipal)?.QuoteId().Split('-').FirstOrDefault();

    var bglBundlingEnabled = bool.TryParse(ConfigurationManager.AppSettings["BundlingEnabled"], out var bundlingEnabled) && bundlingEnabled;

    var pagesWithoutBackAction = new List<string>
{
        Url.Action("Index", "Legal"), Url.Action("AllDone", "Payment"), Url.Action("Index", "SessionTimeout")
    };

    var listOfPageWithAsyncComponents = new List<string>
{
        Url.Action("Index", "AdditionalDetails"),
        Url.Action("Annual", "Payment"),
        Url.Action("AnnualSummary", "Payment"),
        Url.Action("MonthlyInstalment", "Payment"),
        Url.Action("MonthlyInstalmentSummary", "Payment")
    };

    var linkToAlmostThere = Url.Action("AlmostThere", "AdditionalDetails");

    var logoImagePath = $"{tenantConfiguration.ResourceBasePath}logo-brand.svg";
    var listOfPostQuotePages = new[] { "/pricepresentation", "/extras", "/review", "/payment/" };
    var preQuote = listOfPostQuotePages.All(s => !(bool)(Request?.Url?.AbsolutePath?.ToLower().Contains(s)));

    var ninaPreprod = vaConfig.IsVaLive ? string.Empty : $"window.NinaVars.preprod=true;";
    Html.RegisterScript("window.NinaVars=window.NinaVars||{};window.NinaVars.isSelfService=false;" +
                        $"window.NinaVars.isSales=true;{ninaPreprod}window.siteId='{vaConfig.WebChatAccount}';", ScriptLocation.HeadBottom);
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="SvrId" content="TE.NET" />
    <title>@ViewBag.Title - Halifax Insurance</title>
    <link rel="shortcut icon" href="@ConfigurationManager.AppSettings["ApplicationPath"]favi.ico" type="image/x-icon">
    @Styles.Render("~/Content/css")

    @Html.ComponentRenderOneTrust(new ComponentGoogleTagManagerConfiguration
    {
        OneTrustConfiguration = config.GetOneTrustConfiguration(),
    })

    @Scripts.Render("~/bundles/vendor")
    @if (bglBundlingEnabled)
    {
        @Scripts.Render("~/bundles/bgl")
    }
    @Html.ComponentRenderGoogleTagManager(new ComponentGoogleTagManagerConfiguration
    {
        Id = "GoogleTagManager",
        AddOnsList = new List<string>
        {
            "No claims discount protection",
            "Guaranteed Replacement Car",
            "RAC Breakdown Assistance",
            "Keycare",
            "Legal Protection",
            "Personal Accident Cover"
        },
        MarketingSourceSetupList = new List<string> { "comparethemarket", "gocompare", "moneysupermarket", "confusedcom", "quotezonecouk" },
        GtmConfiguration = config.GetGtmConfiguration(),
        TenantConfiguration = tenantConfiguration
    })

    @Html.ComponentRenderGoogleTagManagerDataLayer(new ComponentTagManagerConfiguration
    {
        AddOnsList = new List<string>
        {
            "Legal Protection",
            "No claims discount protection",
            "Price Protection Cover",
            "Guaranteed Replacement Car",
            "RAC Breakdown Assistance",
            "Keycare",
            "Personal Accident Cover"
        },
        QuoteTier = "Standard"
    })

    @Html.RenderRegisteredScripts(ScriptLocation.HeadTop)
    @Html.RenderRegisteredScripts(ScriptLocation.HeadBottom)
    @Html.RegisterTelemetryScript()

    @Html.ComponentRenderGoogleTagManagerTagManager(new ComponentTagManagerConfiguration
    {
        TagManagerScriptUrl = ConfigurationManager.AppSettings["TagManagerScriptUrl"]
    })
</head>
<body>
    @Html.RenderRegisteredScripts(ScriptLocation.BodyTop)
    <a href="#" id="header-focus" class="hide" tabindex="-1">header focus</a>
    <a class="skip-to-main-content" data-testid="header__skip-to-main-content" href="#main-content">Skip to main content</a>
    <div class="all-content">
        <main id="main-content">
            <div class="slide-panel slide-panel__always-open">
                <div class="panel-header panel-header__always-open">
                    <div class="panel-header__wrapper">
                        <a id="slidepanel-close-icon" href="@linkToAlmostThere" class="panel-header__close" aria-label="return to site"></a>
                    </div>
                </div>
                <div class="container">
                    <div class="row">
                        <div class="offset-md-2 col-md-8">
                            @RenderBody()
                        </div>
                    </div>
                </div>
            </div>
            <div id="overlay-pane" class="overlay show"></div>
        </main>

        @Html.Partial("_SlidePanel")

        @if (IsSectionDefined("Footer"))
        {
            @RenderSection("Footer")
        }
        else
        {
            @Html.Partial("_Footer")
        }

        @Html.ComponentRenderPageReloader(new ComponentPageReloaderConfiguration
        {
            Id = "PageReloader",
            TenantConfiguration = tenantConfiguration
        })
        @{
            var componentHoustonConfiguration = new ComponentHoustonConfiguration
            {
                Id = "Houston",
                Brand = vaConfig.BrandName,
                LivePersonBrand = vaConfig.LivePersonBrandName,
                Application = vaConfig.Application,
                JourneySection = "Purchase",
                Product = vaConfig.Product,
                Journey = "Car",
                InvocationPoint = vaConfig.DefaultInvocationPoint,
                PageNamePrefix = "Sales_TE_",
                TenantConfiguration = tenantConfiguration,
                IsPreQuote = preQuote,
                ContactDataUrl = Url.Action("HoustonContactData", "ContactData"),
                OnError = Request.Url.AbsolutePath.ToLower().Contains("error"),
            };
        }
    </div>

    @Html.ComponentRenderHouston(componentHoustonConfiguration)
    <script src="@Url.Content(ConfigurationManager.AppSettings["Nina-Block-Path"])"></script>

    @RenderSection("scripts", required: false)
    @Html.RegisterNavigationOppsPageBackButtonInitScript(pagesWithoutBackAction, listOfPageWithAsyncComponents)
    @Html.RenderRegisteredScripts(ScriptLocation.BodyBottom)

    @Html.Partial("_AjaxErrorScript")

    @Html.ComponentRenderGoogleTagManagerLaunchScript(new ComponentTagManagerConfiguration { })
</body>
</html>