src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Controllers/AdditionalDetailsController.cs
using System.Web.Mvc;
using BGL.Security.Web.Authentication.Controllers;

namespace BGL.Web.Halifax.MotorQuote.Controllers
{
    public class AdditionalDetailsController : SecuredController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult AlmostThere()
        {
            return View();
        }
    }
}

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Controllers/PaymentController.cs
using System.Web.Mvc;
using BGL.Security.Web.Authentication.Controllers;

namespace BGL.Web.Halifax.MotorQuote.Controllers
{
    public class PaymentController : SecuredController
    {
        public ActionResult PaymentSummary()
        {
            return View();
        }

        public ActionResult Annual()
        {
            return View();
        }

        public ActionResult AnnualSummary()
        {
            return View();
        }

        public ActionResult MonthlyInstalment()
        {
            return View();
        }

        public ActionResult MonthlyInstalmentSummary()
        {
            return View();
        }

        public ActionResult MonthlyDeposit()
        {
            return View();
        }

        public ActionResult MonthlyDepositSummary()
        {
            return View();
        }

        public ActionResult AllDone()
        {
            return View();
        }

        public ActionResult Unsuccessful()
        {
            return View();
        }

        public ActionResult PaymentSuccessful()
        {
            return View();
        }

        public ActionResult PolicyCreationPending()
        {
            return View();
        }
    }
}

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Controllers/ReviewController.cs
using System.Web.Mvc;
using BGL.Security.Web.Authentication.Controllers;

namespace BGL.Web.Halifax.MotorQuote.Controllers
{
    public class ReviewController : SecuredController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult SlideReview()
        {
            return View();
        }
    }
}

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Views/AdditionalDetails/AlmostThere.cshtml
@using BGL.Common.Configuration.Interfaces
@using BGL.Components.AdditionalDetails
@using BGL.Components.AdditionalDetails.ViewOptions
@using BGL.Components.CommonComponent
@using BGL.Components.CoverDetails
@model BGL.Components.AdditionalDetails.Models.AdditionalDetailsViewModel

@{
    ViewBag.Title = "Almost there";
    var config = DependencyResolver.Current.GetService<IConfig>();
}

@Html.ComponentRenderAlmostThere(new ComponentAdditionalDetailsConfiguration
{
    Id = "AlmostThere",
    NextPageUrl = Url.Action("PaymentSummary", "Payment"),
    ReviewPageUrl = Url.Action("SlideReview", "Review"),
    TenantConfiguration = config.GetTenantConfiguration(),
    ViewOptions = new ViewOptionsConfiguration()
    {
        NcdSourceThisVehicle = NcdSource.AcceptableProof,
        NcdSourcePreviousVehicle = NcdSource.AcceptableProof,
        NcdSourceCompanyCar = NcdSource.CompanyCarExperiencedDriver
    },
    DataStoreKey = "AlmostThere",
    ErrorConfiguration = new ComponentErrorConfiguration(),
    IsCritical = false

})


<div class="page-section--inner spaced">
    <div class="button-container">
        <button type="submit" class="button button--primary button--large button--right" id="almost-there-button" data-test-id="almost-there-button" href="@Url.Action("PaymentSummary", "Payment")" data-testid="almost-there-button">
            Next: <strong>Payment Details</strong>
        </button>
        <a class="button button--text button--back button--left"
           id="OptionalExtrasBack"
           data-testid="back-button"
           data-cover-details-addon-back-button="review"
           href="@Html.ComponentRenderAddonsBack(new ComponentCoverDetailsExtrasConfiguration()
                 {
                     PreviousStepUrl = "Index",
                     AddonOrder = new Dictionary<string, string>
                     {
                         { "No claims discount protection", "Pncd" },
                         { "Legal Protection", "MotorLegalProtectionSummary" },
                         { "RAC Breakdown Assistance", "BreakdownCoverSummary" },
                         { "Keycare", "KeyCareSummary" }
                     }
                 }).ToString()">
            Back
        </a>
    </div>
</div>

src/BGL.Web.Halifax.MotorQuote/BGL.Web.Halifax.MotorQuote/Views/AdditionalDetails/Index.cshtml
@using BGL.Common.Configuration.Interfaces
@using BGL.Components.AdditionalDetails
@using BGL.Components.AdditionalDetails.ViewOptions

@{
    ViewBag.Title = "Additional Details";
    var config = DependencyResolver.Current.GetService<IConfig>();
}

@Html.ComponentRenderAdditionalDetailsAsync(new ComponentAdditionalDetailsConfiguration
{
    Id = "AdditionalDetails",
    NextPageUrl = Url.Action("PaymentSummary", "Payment"),
    PreviousPageUrl = Url.Action("Index", "Review"),
    TenantConfiguration = config.GetTenantConfiguration(),
    ViewOptions = new ViewOptionsConfiguration()
    {
        NcdSourceThisVehicle = NcdSource.AcceptableProof,
        NcdSourcePreviousVehicle = NcdSource.AcceptableProof,
        NcdSourceCompanyCar = NcdSource.AcceptableProof
    }
})