src/BGL.Web.PostOffice.MotorQuote/BGL.Web.PostOffice.MotorQuote/Controllers/YourCoverController.cs
using System.Web.Mvc;
using BGL.Security.Web.Authentication.Controllers;

namespace BGL.Web.PostOffice.MotorQuote.Controllers
{
    public class YourCoverController : SecuredController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MainDriver()
        {
            return View();
        }

        public ActionResult CoverLevel()
        {
            return View();
        }

        public ActionResult CoverExcesses()
        {
            return View();
        }

        public ActionResult AnnualMileage()
        {
            return View();
        }

        public ActionResult RegisteredKeeperRelationship()
        {
            return View();
        }

        public ActionResult AboutRegisteredKeeper()
        {
            return View();
        }

        public ActionResult RegisteredKeeperMaritalStatus()
        {
            return View();
        }

        public ActionResult RegisteredKeeperSameAddress()
        {
            return View();
        }

        public ActionResult VehicleUse()
        {
            return View();
        }

        public ActionResult NcdYears()
        {
            return View();
        }

        public ActionResult NcdSource()
        {
            return View();
        }

        public ActionResult OtherVehicles()
        {
            return View();
        }

        public ActionResult CoverStartDate()
        {
            return View();
        }

        public ActionResult YearsBusinessEstablished()
        {
            return View();
        }

        public ActionResult CarriageOfDangerousGoods()
        {
            return View();
        }
    }
}

src/BGL.Web.PostOffice.MotorQuote/BGL.Web.PostOffice.MotorQuote/Controllers/YourDetailsController.cs
using System.Web.Mvc;
using BGL.Security.Web.Authentication.Controllers;

namespace BGL.Web.PostOffice.MotorQuote.Controllers
{
    public class YourDetailsController : SecuredController
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult MaritalStatus()
        {
            return View();
        }

        public ActionResult Address()
        {
            return View();
        }

        public ActionResult ConfirmedAddress()
        {
            return View();
        }

        public ActionResult HomeOwner()
        {
            return View();
        }

        public ActionResult InformationSource()
        {
            return View();
        }

        public ActionResult UkResident()
        {
            return View();
        }

        public ActionResult EmploymentStatus()
        {
            return View();
        }

        public ActionResult EmploymentOccupation()
        {
            return View();
        }

        public ActionResult EmploymentBusinessType()
        {
            return View();
        }

        public ActionResult PartTimeOccupation()
        {
            return View();
        }

        public ActionResult PartTimeOccupationType()
        {
            return View();
        }

        public ActionResult PartTimeBusinessType()
        {
            return View();
        }

        public ActionResult LicenceType()
        {
            return View();
        }

        public ActionResult LicenceDate()
        {
            return View();
        }

        public ActionResult LicenceNumber()
        {
            return View();
        }

        public ActionResult MedicalCondition()
        {
            return View();
        }

        public ActionResult MedicalConditionDvlaNotified()
        {
            return View();
        }

        public ActionResult DeclinedInsurance()
        {
            return View();
        }

        public ActionResult MotorClaims()
        {
            return View();
        }

        public ActionResult MotorConvictions()
        {
            return View();
        }

        public ActionResult CriminalConvictions()
        {
            return View();
        }

        public ActionResult AdditionalDrivers()
        {
            return View();
        }
    }
}

src/BGL.Web.PostOffice.MotorQuote/BGL.Web.PostOffice.MotorQuote/Controllers/YourVanController.cs
using System.Web.Mvc;
using BGL.Security.Web.Authentication.Controllers;

namespace BGL.Web.PostOffice.MotorQuote.Controllers
{
    public class YourVanController : SecuredController
    {
        public ActionResult VehicleLookup()
        {
            return View();
        }

        public ActionResult VehicleDetails()
        {
            return View();
        }

        public ActionResult OvernightParking()
        {
            return View();
        }
    }
}

src/BGL.Web.PostOffice.MotorQuote/BGL.Web.PostOffice.MotorQuote/Views/YourVan/OvernightParking.cshtml
@using BGL.Common.Configuration.Interfaces
@using BGL.Common.Utility.Extensions
@using BGL.Components.VehicleDetails
@using BGL.Components.VehicleDetails.Enums
@{
    ViewBag.Title = "Overnight Parking";
    Layout = "~/Views/Shared/_LayoutDirectToSite.cshtml";
    var tenantConfiguration = DependencyResolver.Current.GetService<IConfig>().GetTenantConfiguration();
}

<div class="page-section">
    <div class="page-section--inner narrow">
        @Html.ComponentRenderOvernightParking(new ComponentVehicleDetailsConfiguration
        {
            Id = "OvernightParking",
            TenantConfiguration = tenantConfiguration,
            JourneyType = JourneyTypes.MultiStepEdit,
            DataStoreKey = "YourVanParking",
            NextStepUrl = Url.Action("Index", "YourCover"),
            PreviousStepUrl = $"{Url.Action("VehicleDetails", "YourVan")}#value"
        })
    </div>
</div>

src/BGL.Web.PostOffice.MotorQuote/BGL.Web.PostOffice.MotorQuote/Views/YourVan/VehicleDetails.cshtml
@using BGL.Common.Configuration.Interfaces
@using BGL.Common.Utility.Extensions
@using BGL.Components.VehicleDetails
@using BGL.Components.VehicleDetails.Enums
@using BGL.Web.PostOffice.MotorQuote.Constants
@{
    ViewBag.Title = "Vehicle Details";
    Layout = "~/Views/Shared/_LayoutDirectToSite.cshtml";
    var tenantConfiguration = DependencyResolver.Current.GetService<IConfig>().GetTenantConfiguration();
}

<div class="page-section">
    <div class="page-section--inner" aria-live="polite">
        @Html.ComponentRenderVehicleLookup(new ComponentVehicleDetailsConfiguration
        {
            Id = "VehicleDetails",
            ManufactureListInUpperCase = new List<string>
            {
                "BMW", "SEAT", "MAN"
            },
            ManufacturerKeys = new List<string>
            {
                "FO",
                "VA",
                "VW",
                "PE",
                "NI",
                "BM",
                "R1",
                "CI",
                "TO",
                "AU",
                "ME",
                "HO",
                "FI",
            },
            WrongVehicleTypeForVanInsValidationErrorMessage = BrandConstants.WrongVehicleTypeForVanInsValidationErrorMessage,
            WrongVehicleTypeForCarInsValidationErrorMessage = BrandConstants.WrongVehicleTypeForCarInsValidationErrorMessage,
            CarErrorMessageUrl = BrandConstants.CarErrorMessageUrl,
            VanErrorMessageUrl = BrandConstants.VanErrorMessageUrl,
            TenantConfiguration = tenantConfiguration,
            SummaryButtonText = "Continue",
            ModificationButtonText = "Continue",
            DataStoreKey = "YourVan",
            JourneyType = JourneyTypes.MultiStepEdit,
            NextStepUrl = Url.Action("OvernightParking", "YourVan"),
            PreviousStepUrl = Url.Action("VehicleLookup", "YourVan"),
            ComponentUrl = Url.Action("VehicleDetails", "YourVan"),
            SearchSummaryUrl = Url.Action("SearchSummary", "VehicleDetailsComponentSearching"),
            ModificationsUrl = Url.Action("Modifications", "VehicleDetailsComponentModifications"),
            PurchasedDateUrl = Url.Action("PurchaseDate", "VehicleDetailsComponentPurchaseDate"),
            EditValueUrl = Url.Action("EditVehicleValue", "VehicleDetailsComponentValue"),
            VehicleBodyTypeUrl = Url.Action("VehicleBodyType", "VehicleDetailsComponentVehicleBodyType"),
            NumberOfSeatsUrl = Url.Action("NumberOfSeats", "VehicleDetailsComponentNumberOfSeats")
        })
    </div>
</div>

src/BGL.Web.PostOffice.MotorQuote/BGL.Web.PostOffice.MotorQuote/Views/YourVan/VehicleLookup.cshtml
@using BGL.Common.Configuration.Interfaces
@using BGL.Common.Utility.Extensions
@using BGL.Components.VehicleDetails
@using BGL.Components.VehicleDetails.Enums
@using BGL.Web.PostOffice.MotorQuote.Constants
@{
    ViewBag.Title = "Vehicle Lookup";
    Layout = "~/Views/Shared/_LayoutDirectToSite.cshtml";
    var tenantConfiguration = DependencyResolver.Current.GetService<IConfig>().GetTenantConfiguration();
}

<div class="page-section">
    <div class="page-section--inner">
        @Html.ComponentRenderVehicleSearching(new ComponentVehicleDetailsConfiguration
        {
            Id = "VehicleDetails",
            ManufactureListInUpperCase = new List<string>
            {
                "BMW", "SEAT", "MAN"
            },
            ManufacturerKeys = new List<string>
            {
                "FO",
                "VA",
                "VW",
                "PE",
                "NI",
                "BM",
                "R1",
                "CI",
                "TO",
                "AU",
                "ME",
                "HO",
                "FI",
            },
            WrongVehicleTypeForVanInsValidationErrorMessage = BrandConstants.WrongVehicleTypeForVanInsValidationErrorMessage,
            WrongVehicleTypeForCarInsValidationErrorMessage = BrandConstants.WrongVehicleTypeForCarInsValidationErrorMessage,
            CarErrorMessageUrl = BrandConstants.CarErrorMessageUrl,
            VanErrorMessageUrl = BrandConstants.VanErrorMessageUrl,
            TenantConfiguration = tenantConfiguration,
            SummaryButtonText = "Continue",
            ModificationButtonText = "Continue",
            DataStoreKey = "YourVan",
            JourneyType = JourneyTypes.MultiStepEdit,
            NextStepUrl = Url.Action("VehicleDetails", "YourVan"),
            PreviousStepUrl = Url.Action("AdditionalDrivers", "YourDetails"),
            ComponentUrl = Url.Action("VehicleDetails", "YourVan")
        })
    </div>
</div>